[functions]
node_bundler = "esbuild"
external_node_modules = ["sharp"]
included_files = ["node_modules/sharp/**/*"]

[build.environment]
NODE_VERSION = "20"

[functions."analyze-pose"]
included_files = []
external_node_modules = []
node_bundler = "esbuild"
memory = 1024 # Increase memory limit
timeout = 30 # Increase timeout if needed

[[redirects]]
force = true
from = "/*"
status = 200
to = "/index.html"
